 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: demoasset-be
   namespace: demoasset
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: demoasset-be
   template:
     metadata:
       labels:
         app: demoasset-be
     spec:
       containers:
       - name: demoasset-be
         image: demoasset-be-complete:latest
         imagePullPolicy: Never
         ports:
         - containerPort: 9080
         env:
         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
             secretKeyRef:
               name: mysqlcreds
               key: password
         resources:
           limits:
             memory: "400Mi"
             cpu: "200m"
           requests:
             memory: "400Mi"
             cpu: "100m"